'use client'

import { useState } from 'react'
import Image from 'next/image'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface NewsItem {
  id: number
  title: string
  description: string
  highlights: string[]
  category: string
}

export default function NewsSummaryCard({ news }: { news: NewsItem }) {
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState('')

  const handleAskQuestion = () => {
    // Simulate API call to LLM
    setTimeout(() => {
      setAnswer(`This is a simulated answer to your question: "${question}" about ${news.title}. In a real application, this would be generated by an AI model based on the news content and your specific query.`)
    }, 1000)
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{news.title}</CardTitle>
        <CardDescription>{news.description}</CardDescription>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible>
          <AccordionItem value="highlights">
            <AccordionTrigger>Key Highlights</AccordionTrigger>
            <AccordionContent>
              <ul className="list-disc pl-5">
                {news.highlights.map((highlight, index) => (
                  <li key={index}>{highlight}</li>
                ))}
              </ul>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="qa">
            <AccordionTrigger>Ask a Question</AccordionTrigger>
            <AccordionContent>
              <div className="space-y-4">
                <div className="flex space-x-2">
                  <Input
                    type="text"
                    placeholder="Ask a question about this news"
                    value={question}
                    onChange={(e) => setQuestion(e.target.value)}
                  />
                  <Button onClick={handleAskQuestion}>Ask</Button>
                </div>
                {answer && (
                  <div className="bg-muted p-4 rounded-md">
                    <p>{answer}</p>
                  </div>
                )}
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
        <div className="mt-4">
          <h4 className="font-semibold mb-2">Related Image</h4>
          <Image
            src={`https://source.unsplash.com/random/800x400?${news.category}`}
            alt={news.title}
            width={800}
            height={400}
            className="rounded-md"
          />
        </div>
      </CardContent>
    </Card>
  )
}

